<?php
/**
 * CheckoutAgreementsDataAgreementInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Webgriffe\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Webgriffe\MagentoApiClient;

/**
 * CheckoutAgreementsDataAgreementInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface AgreementInterface
/**
 * @package     Webgriffe\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutAgreementsDataAgreementInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CheckoutAgreementsDataAgreementInterface"
     */
    public function testCheckoutAgreementsDataAgreementInterface()
    {

    }

    /**
     * Test attribute "agreementId"
     */
    public function testPropertyAgreementId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "contentHeight"
     */
    public function testPropertyContentHeight()
    {

    }

    /**
     * Test attribute "checkboxText"
     */
    public function testPropertyCheckboxText()
    {

    }

    /**
     * Test attribute "isActive"
     */
    public function testPropertyIsActive()
    {

    }

    /**
     * Test attribute "isHtml"
     */
    public function testPropertyIsHtml()
    {

    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
