<?php
/**
 * CheckoutDataShippingInformationInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Webgriffe\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Webgriffe\MagentoApiClient;

/**
 * CheckoutDataShippingInformationInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface ShippingInformationInterface
/**
 * @package     Webgriffe\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutDataShippingInformationInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CheckoutDataShippingInformationInterface"
     */
    public function testCheckoutDataShippingInformationInterface()
    {

    }

    /**
     * Test attribute "shippingAddress"
     */
    public function testPropertyShippingAddress()
    {

    }

    /**
     * Test attribute "billingAddress"
     */
    public function testPropertyBillingAddress()
    {

    }

    /**
     * Test attribute "shippingMethodCode"
     */
    public function testPropertyShippingMethodCode()
    {

    }

    /**
     * Test attribute "shippingCarrierCode"
     */
    public function testPropertyShippingCarrierCode()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

    /**
     * Test attribute "customAttributes"
     */
    public function testPropertyCustomAttributes()
    {

    }

}
