<?php
/**
 * GiftMessageDataMessageExtensionInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Webgriffe\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Webgriffe\MagentoApiClient;

/**
 * GiftMessageDataMessageExtensionInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description ExtensionInterface class for @see \\Magento\\GiftMessage\\Api\\Data\\MessageInterface
/**
 * @package     Webgriffe\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GiftMessageDataMessageExtensionInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GiftMessageDataMessageExtensionInterface"
     */
    public function testGiftMessageDataMessageExtensionInterface()
    {

    }

    /**
     * Test attribute "entityId"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "entityType"
     */
    public function testPropertyEntityType()
    {

    }

    /**
     * Test attribute "wrappingId"
     */
    public function testPropertyWrappingId()
    {

    }

    /**
     * Test attribute "wrappingAllowGiftReceipt"
     */
    public function testPropertyWrappingAllowGiftReceipt()
    {

    }

    /**
     * Test attribute "wrappingAddPrintedCard"
     */
    public function testPropertyWrappingAddPrintedCard()
    {

    }

}
