<?php
/**
 * QuoteDataPaymentInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Webgriffe\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Webgriffe\MagentoApiClient;

/**
 * QuoteDataPaymentInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface PaymentInterface
/**
 * @package     Webgriffe\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteDataPaymentInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataPaymentInterface"
     */
    public function testQuoteDataPaymentInterface()
    {

    }

    /**
     * Test attribute "poNumber"
     */
    public function testPropertyPoNumber()
    {

    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {

    }

    /**
     * Test attribute "additionalData"
     */
    public function testPropertyAdditionalData()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
