<?php
/**
 * RmaDataItemInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Webgriffe\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Webgriffe\MagentoApiClient;

/**
 * RmaDataItemInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface CategoryInterface
/**
 * @package     Webgriffe\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RmaDataItemInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RmaDataItemInterface"
     */
    public function testRmaDataItemInterface()
    {

    }

    /**
     * Test attribute "entityId"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "rmaEntityId"
     */
    public function testPropertyRmaEntityId()
    {

    }

    /**
     * Test attribute "orderItemId"
     */
    public function testPropertyOrderItemId()
    {

    }

    /**
     * Test attribute "qtyRequested"
     */
    public function testPropertyQtyRequested()
    {

    }

    /**
     * Test attribute "qtyAuthorized"
     */
    public function testPropertyQtyAuthorized()
    {

    }

    /**
     * Test attribute "qtyApproved"
     */
    public function testPropertyQtyApproved()
    {

    }

    /**
     * Test attribute "qtyReturned"
     */
    public function testPropertyQtyReturned()
    {

    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {

    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {

    }

    /**
     * Test attribute "resolution"
     */
    public function testPropertyResolution()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
