<?php
/**
 * SalesDataInvoiceInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Webgriffe\MagentoApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Enterprise
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Webgriffe\MagentoApiClient;

/**
 * SalesDataInvoiceInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Invoice interface. An invoice is a record of the receipt of payment for an order.
/**
 * @package     Webgriffe\MagentoApiClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesDataInvoiceInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SalesDataInvoiceInterface"
     */
    public function testSalesDataInvoiceInterface()
    {

    }

    /**
     * Test attribute "baseCurrencyCode"
     */
    public function testPropertyBaseCurrencyCode()
    {

    }

    /**
     * Test attribute "baseDiscountAmount"
     */
    public function testPropertyBaseDiscountAmount()
    {

    }

    /**
     * Test attribute "baseGrandTotal"
     */
    public function testPropertyBaseGrandTotal()
    {

    }

    /**
     * Test attribute "baseDiscountTaxCompensationAmount"
     */
    public function testPropertyBaseDiscountTaxCompensationAmount()
    {

    }

    /**
     * Test attribute "baseShippingAmount"
     */
    public function testPropertyBaseShippingAmount()
    {

    }

    /**
     * Test attribute "baseShippingDiscountTaxCompensationAmnt"
     */
    public function testPropertyBaseShippingDiscountTaxCompensationAmnt()
    {

    }

    /**
     * Test attribute "baseShippingInclTax"
     */
    public function testPropertyBaseShippingInclTax()
    {

    }

    /**
     * Test attribute "baseShippingTaxAmount"
     */
    public function testPropertyBaseShippingTaxAmount()
    {

    }

    /**
     * Test attribute "baseSubtotal"
     */
    public function testPropertyBaseSubtotal()
    {

    }

    /**
     * Test attribute "baseSubtotalInclTax"
     */
    public function testPropertyBaseSubtotalInclTax()
    {

    }

    /**
     * Test attribute "baseTaxAmount"
     */
    public function testPropertyBaseTaxAmount()
    {

    }

    /**
     * Test attribute "baseTotalRefunded"
     */
    public function testPropertyBaseTotalRefunded()
    {

    }

    /**
     * Test attribute "baseToGlobalRate"
     */
    public function testPropertyBaseToGlobalRate()
    {

    }

    /**
     * Test attribute "baseToOrderRate"
     */
    public function testPropertyBaseToOrderRate()
    {

    }

    /**
     * Test attribute "billingAddressId"
     */
    public function testPropertyBillingAddressId()
    {

    }

    /**
     * Test attribute "canVoidFlag"
     */
    public function testPropertyCanVoidFlag()
    {

    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "discountAmount"
     */
    public function testPropertyDiscountAmount()
    {

    }

    /**
     * Test attribute "discountDescription"
     */
    public function testPropertyDiscountDescription()
    {

    }

    /**
     * Test attribute "emailSent"
     */
    public function testPropertyEmailSent()
    {

    }

    /**
     * Test attribute "entityId"
     */
    public function testPropertyEntityId()
    {

    }

    /**
     * Test attribute "globalCurrencyCode"
     */
    public function testPropertyGlobalCurrencyCode()
    {

    }

    /**
     * Test attribute "grandTotal"
     */
    public function testPropertyGrandTotal()
    {

    }

    /**
     * Test attribute "discountTaxCompensationAmount"
     */
    public function testPropertyDiscountTaxCompensationAmount()
    {

    }

    /**
     * Test attribute "incrementId"
     */
    public function testPropertyIncrementId()
    {

    }

    /**
     * Test attribute "isUsedForRefund"
     */
    public function testPropertyIsUsedForRefund()
    {

    }

    /**
     * Test attribute "orderCurrencyCode"
     */
    public function testPropertyOrderCurrencyCode()
    {

    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "shippingAddressId"
     */
    public function testPropertyShippingAddressId()
    {

    }

    /**
     * Test attribute "shippingAmount"
     */
    public function testPropertyShippingAmount()
    {

    }

    /**
     * Test attribute "shippingDiscountTaxCompensationAmount"
     */
    public function testPropertyShippingDiscountTaxCompensationAmount()
    {

    }

    /**
     * Test attribute "shippingInclTax"
     */
    public function testPropertyShippingInclTax()
    {

    }

    /**
     * Test attribute "shippingTaxAmount"
     */
    public function testPropertyShippingTaxAmount()
    {

    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {

    }

    /**
     * Test attribute "storeCurrencyCode"
     */
    public function testPropertyStoreCurrencyCode()
    {

    }

    /**
     * Test attribute "storeId"
     */
    public function testPropertyStoreId()
    {

    }

    /**
     * Test attribute "storeToBaseRate"
     */
    public function testPropertyStoreToBaseRate()
    {

    }

    /**
     * Test attribute "storeToOrderRate"
     */
    public function testPropertyStoreToOrderRate()
    {

    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {

    }

    /**
     * Test attribute "subtotalInclTax"
     */
    public function testPropertySubtotalInclTax()
    {

    }

    /**
     * Test attribute "taxAmount"
     */
    public function testPropertyTaxAmount()
    {

    }

    /**
     * Test attribute "totalQty"
     */
    public function testPropertyTotalQty()
    {

    }

    /**
     * Test attribute "transactionId"
     */
    public function testPropertyTransactionId()
    {

    }

    /**
     * Test attribute "updatedAt"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {

    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {

    }

    /**
     * Test attribute "extensionAttributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
